version: '3.8'

services:
  places-api:
    build: .
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/places_api_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      api_net:

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: places_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      api_net:

networks:
  api_net: